CREATE TABLE Missions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Difficulty VARCHAR(100) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Reward VARCHAR(255),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NULL,
    INDEX (Difficulty),
    INDEX (Location)
);

CREATE TABLE Factions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Region VARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MissionFactions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    MissionId INT NOT NULL,
    FactionId INT NOT NULL,
    FOREIGN KEY (MissionId) REFERENCES Missions(Id) ON DELETE CASCADE,
    FOREIGN KEY (FactionId) REFERENCES Factions(Id) ON DELETE CASCADE
);



