// <auto-generated />
using System;
using AcMissionsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcMissionsApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AcMissionsApp.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Factions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 9, 29, 2, 700, DateTimeKind.Local).AddTicks(784),
                            Name = "Assassins",
                            Region = "Moyen-Orient"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 9, 29, 2, 700, DateTimeKind.Local).AddTicks(1451),
                            Name = "Templiers",
                            Region = "Europe"
                        });
                });

            modelBuilder.Entity("AcMissionsApp.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reward")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 9, 29, 2, 700, DateTimeKind.Local).AddTicks(6202),
                            Description = "Altaïr doit infiltrer Acre pour éliminer Garnier de Naplouse.",
                            Difficulty = "Difficile",
                            Location = "Acre",
                            Title = "La Croisade du Roi Richard"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 9, 29, 2, 700, DateTimeKind.Local).AddTicks(6943),
                            Description = "Ezio élimine les lieutenants de Savonarole à Florence.",
                            Difficulty = "Moyenne",
                            Location = "Florence",
                            Title = "Le Procès de Savonarole"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 9, 29, 2, 700, DateTimeKind.Local).AddTicks(6951),
                            Description = "Connor poursuit Charles Lee à New York.",
                            Difficulty = "Difficile",
                            Location = "New York",
                            Title = "La Traque de Charles Lee"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 23, 9, 29, 2, 700, DateTimeKind.Local).AddTicks(6954),
                            Description = "Bayek infiltre une réception pour Cléopâtre.",
                            Difficulty = "Facile",
                            Location = "Alexandrie",
                            Title = "Le Banquet de Cléopâtre"
                        });
                });

            modelBuilder.Entity("AcMissionsApp.Models.MissionFaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("MissionId");

                    b.ToTable("MissionFactions");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FactionId = 1,
                            MissionId = 1
                        },
                        new
                        {
                            Id = -2,
                            FactionId = 1,
                            MissionId = 2
                        },
                        new
                        {
                            Id = -3,
                            FactionId = 1,
                            MissionId = 3
                        },
                        new
                        {
                            Id = -4,
                            FactionId = 1,
                            MissionId = 4
                        });
                });

            modelBuilder.Entity("AcMissionsApp.Models.MissionFaction", b =>
                {
                    b.HasOne("AcMissionsApp.Models.Faction", "Faction")
                        .WithMany("MissionFactions")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcMissionsApp.Models.Mission", "Mission")
                        .WithMany("MissionFactions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("AcMissionsApp.Models.Faction", b =>
                {
                    b.Navigation("MissionFactions");
                });

            modelBuilder.Entity("AcMissionsApp.Models.Mission", b =>
                {
                    b.Navigation("MissionFactions");
                });
#pragma warning restore 612, 618
        }
    }
}
